language: python
python:
  - "3.8"
  - "3.9"
install:
  - pip install poetry
  - poetry install
services:
  - mongodb
script:
  - black --check -v monquery/ test/
  - mypy monquery
  - pytest --cov monquery/ --cov-report xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
